services:
  fastapi:
    build: .
    container_name: home-air-monitor-api
    image: home-air-monitor-api:latest
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: unless-stopped